<#
-----------------------------------------------------------------------------
This script sends files from a local folder to a remote server.
It can also syncronize files by replacing the put command with the following:
"synchronize remote -delete $($localFolder) $($remoteFolder)"
 
The script depends on WinSCP.
Use WinSCP to generate connection string and host key.

Author: lucas@hokerberg.com
Created: 2020-07-10
-----------------------------------------------------------------------------
#>

# Define static variables
$logFile = "C:\Logs\transfer.log" # Absolute path to log file
$connString = "sftp://username:password@server.host.com/" # Connection string as been generated by WinSCP
$hostKey = "ssh-ab12345 123 xxxyyy+zzz=" # Host key as been generated by WinSCP
$localFolder = "C:\Source" # Absolut path to local folder without trailing slash
$remoteFolder = "/destination" # Absolute path to remote folder without trailing slash

# Connect to remote server and send files
& "C:\Program Files (x86)\WinSCP\WinSCP.com" `
  /log=$($logFile) /loglevel=-1 /logsize=2*5M /ini=nul `
  /command `
    "open $($connString) -hostkey=`"`"$($hostKey)`"`"" `
    "put $($localFolder)\* $($remoteFolder)/" `
    "exit"

# Exit with result
$winscpResult = $LastExitCode
exit $winscpResult
